### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by alanking** [irods/irods_docs#20]
- [x] Deprecation/end of life (see #124)
- [x] Development environment (see https://github.com/irods/irods_docs/issues/219)
- [x] Building and installing iRODS (https://github.com/irods/irods_docs/issues/220)
- [x] Onboarding new developers (https://github.com/irods/irods_docs/issues/221)
- [x] Testing environment (https://github.com/irods/irods_docs/issues/222)
- [x] How to use Github
- [x] How to use rr/debugging tools (https://github.com/irods/irods_docs/issues/223)
- [x] Valgrind (https://github.com/irods/irods_docs/issues/224)
- [x] Static analysis (Clang) (https://github.com/irods/irods_docs/issues/225)
- [x] Running (and adding) tests (https://github.com/irods/irods_docs/issues/226)

**Comment by alanking** [comment]
Could probably use some documentation around plugin operations as well as instructions for generic (and specific) plugin implementation.

**Comment by korydraughn** [comment]
this should include documentation on coding conventions, for example, the JSON property name for instructing the server to execute the operation as an administrator should be *admin_mode* and accept a boolean value.

**Comment by trel** [comment]
best practices section...
 - should include target library advice / do and do nots. 
     -  https://github.com/irods/irods/issues/6218#issuecomment-1056978356

**Comment by korydraughn** [comment]
add notes to the developer docs about invoking external programs from C++ code.
